export {
  mdiAccount as user,
  mdiAccountMultiple as users,
  mdiAccountSettings as updateStatus,
  mdiAlertCircle as report,
  mdiBookmark as bookmark,
  mdiClose as close,
  mdiCodeTags as console,
  mdiComment as message,
  mdiForum as channels,
  mdiInformation as about,
  mdiLogout as logout,
  mdiMenu as menu,
  mdiMinusCircle as ignore,
  mdiSettings as settings,
} from "@mdi/js"
