name: run the things and make sure they aren't broken
on: [push]
env:
  CI: true
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm i -g pnpm
      - run: pnpm i
      - run: pnpm run ci
