name: run the things and make sure they aren't broken
on: [push]
env:
  CI: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@main
        with:
          node-version: "14"
      - run: npm i -g pnpm
      - run: pnpm install
      - run: pnpm run ci
